@startuml
'https://plantuml.com/class-diagram

interface Pattern {
    +String name
    +Map<Double, Pattern> nextPatternProbability
}
class RuebenMusterVorhersage {
    -Pattern previousPattern
    -Pattern nextPattern
    -boolean IsFirstPurchase
}

class RuebenPreisRechner {
    -Integer basePrice
    -Pattern currentPattern
    -Map<LocalDateTime, Integer> sellingPrices

}


@enduml